### ISSUE TITLE
加载插件出错

### ISSUE THREAD

**Issue by HanYaaaaaaa** [bot-ssttkkl/nonebot-plugin-access-control#26]
python版本：3.8.10
报错如下：[ERROR] nonebot | Failed to import "nonebot_plugin_access_control"
Traceback (most recent call last):
  File "<string>", line 18, in <module>
  File "/usr/kabobot/.venv/lib/python3.8/site-packages/nonebot/plugin/load.py", line 130, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "/usr/kabobot/.venv/lib/python3.8/site-packages/nonebot/plugin/load.py", line 64, in load_all_plugins
    return manager.load_all_plugins()
  File "/usr/kabobot/.venv/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 176, in load_all_plugins
    return set(
  File "/usr/kabobot/.venv/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 177, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "/usr/kabobot/.venv/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 142, in load_plugin
    module = importlib.import_module(name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/usr/kabobot/.venv/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 242, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/kabobot/.venv/lib/python3.8/site-packages/nonebot_plugin_access_control/__init__.py", line 35, in <module>
    from . import patcher
  File "/usr/kabobot/.venv/lib/python3.8/site-packages/nonebot_plugin_access_control/patcher.py", line 7
    @get_driver().on_startup
                 ^
SyntaxError: invalid syntax

**Comment by ssttkkl** [comment]
python需要3.9以上
