### ISSUE TITLE
【bug？】消息体无法解析

### ISSUE THREAD

**Issue by Todysheep** [bot-ssttkkl/nonebot-plugin-access-control#32]
发送消息为：/ac limit add --sbj all --srv nonebot_plugin_memes --span 90s --limit 2
前端：LLOneBot v3.26.5
```
06-15 13:43:09 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot_plugin_access_control.matcher, lineno=9)
06-15 13:43:09 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_access_control.matcher, lineno=9) running complete
06-15 13:43:09 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_access_control.matcher, lineno=9) failed.
Traceback (most recent call last):
  File "<string>", line 17, in <module>
  File "C:\Pyhton\Lib\site-packages\nonebot\__init__.py", line 335, in run
    get_driver().run(*args, **kwargs)
  File "C:\Pyhton\Lib\site-packages\nonebot\drivers\fastapi.py", line 186, in run
    uvicorn.run(
  File "C:\Pyhton\Lib\site-packages\uvicorn\main.py", line 577, in run
    server.run()
  File "C:\Pyhton\Lib\site-packages\uvicorn\server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Pyhton\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
  File "C:\Pyhton\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "C:\Pyhton\Lib\asyncio\base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "C:\Pyhton\Lib\asyncio\windows_events.py", line 322, in run_forever
    super().run_forever()
  File "C:\Pyhton\Lib\asyncio\base_events.py", line 641, in run_forever
    self._run_once()
  File "C:\Pyhton\Lib\asyncio\base_events.py", line 1987, in _run_once
    handle._run()
  File "C:\Pyhton\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Pyhton\Lib\site-packages\nonebot\message.py", line 476, in check_and_run_matcher
    await _run_matcher(
> File "C:\Pyhton\Lib\site-packages\nonebot\message.py", line 428, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\Pyhton\Lib\site-packages\nonebot\internal\matcher\matcher.py", line 850, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\Pyhton\Lib\site-packages\nonebot\internal\matcher\matcher.py", line 825, in simple_run
    await handler(
  File "C:\Pyhton\Lib\site-packages\nonebot\dependencies\__init__.py", line 94, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "C:\Pyhton\Lib\site-packages\nonebot_plugin_access_control\matcher.py", line 41, in handle_cmd
    await send_multipart(matcher, f.getvalue())
  File "C:\Pyhton\Lib\site-packages\nonebot_plugin_access_control\matcher.py", line 27, in send_multipart
    await matcher.send(msg.strip())
  File "C:\Pyhton\Lib\site-packages\nonebot\internal\matcher\matcher.py", line 566, in send
    return await bot.send(event=event, message=_message, **kwargs)
  File "C:\Pyhton\Lib\site-packages\nonebot\adapters\onebot\v11\bot.py", line 228, in send
    return await self.__class__.send_handler(self, event, message, **kwargs)
  File "C:\Pyhton\Lib\site-packages\nonebot\adapters\onebot\v11\bot.py", line 181, in send
    return await bot.send_msg(**params)
  File "C:\Pyhton\Lib\site-packages\nonebot\internal\adapter\bot.py", line 122, in call_api
    raise exception
  File "C:\Pyhton\Lib\site-packages\nonebot\internal\adapter\bot.py", line 97, in call_api
    result = await self.adapter._call_api(self, api, **data)
  File "C:\Pyhton\Lib\site-packages\nonebot\adapters\onebot\v11\adapter.py", line 147, in _call_api
    return handle_api_result(await self._result_store.fetch(seq, timeout))
  File "C:\Pyhton\Lib\site-packages\nonebot\adapters\onebot\v11\utils.py", line 58, in handle_api_result
    raise ActionFailed(**result)
nonebot.adapters.onebot.v11.exception.ActionFailed: ActionFailed(status='failed', retcode=1200, data=None, message='消息体无法解析，请检查是否发送了不支持的消息类型', wording='消息体无法解析，请检查是否发送了不支持的消息类型', echo='10')
```

**Comment by ssttkkl** [comment]
测试napcat是正常的（
